dchristiansen/Team1-SCOTS-Capstone-CS4970

- public/EdgeRACTrainer.js
> renamed play game function to playGame

- public/game/behaviours/ScoreCalculator.js
- public/game/behaviours/TapHandler.js
- public/game/behaviours/Timer.js
- public/game/data/TapInfo.js
- public/game/scenes/PlayScene.js
- public/graph.js
Implementing cycles into the game
> Feature cycles

- public/EdgeRACTrainer.js
- public/game/behaviours/CircleBehaviour.js
- public/game/scenes/PlayScene.js
Implemented the toggle for feedback in the parameter page
> Feature feedback toggle

- public/graph.js
score page output data are now rounded to the correct number of digits.
> Fixed graph data formatting bug

- public/Data.js
- public/databaseTest.html
- public/databaseTest.js
Take a look at databaseTest.js for how to work with function.
Currently I have my retrieval functions return a Promise. I will take a look soon to see if I can change this, for now you should be able to access the array of assignments or sessions that is returned. Take a look at the Data.js for exact return format. The field names are the same as what is inserted in the create functions.
I will add more documentation soon
> Firebase database functions

- public/Data.js
- public/databaseTest.js
It ended up being a simple fix. You should be able to access the returned objects like normal now. See the database.js for an example.
> Changed db get functions to return array instead of promise

- public/Data.js
- public/databaseTest.html
- public/databaseTest.js
Implemented async/await pattern for database queries, not sure if this is best practice. Updated databaseTest.js to reflect how to call db functions from client
@gabrielp3rez any ideas on this?
For calling these functions from client, the calls need to be wrapped in an async function. See the databaseTest.js for details.
Open for ideas on how to improve
> Implemented async/await pattern for database queries

- public/rPortal.html
- public/rPortal.js
Still some formatting work to be done. Table rows should be clickable instead of just text of userID. User page needs to be created for userID to link to. Table should be searchable. Table should maybe be sorted.
> rPortal.html now automatically populates user list from firestore.

- public/EdgeRACTrainer.js
Prevents users from directly going to start.html without setting parameters or selecting an assignment
> Fixed the issue with going directly to start.html

- functions/index.js
- public/userData.html
- public/userData.js
Delete user from users table and change user password from the researcher portal. Will add delete functionality later
> More admin work

- public/Data.js
- public/createassignment.html
- public/createassignment.js
- public/rPortal.html
> Create Assignment feature

- public/Data.js
- public/assignments.html
- public/assignments.js
- public/editAssignment.html
- public/editAssignment.js
- public/rPortal.html
Edit assignments and assign them to users
> Feature edit assignment

- public/game/behaviours/Timer.js
- public/graph.js
- public/results.html
Fixed the bug where the game would never end when playing without logging in
> Fixed game finish bug when not logged in

- public/assignments.js
- public/createassignment.js
- public/editAssignment.html
- public/editAssignment.js
- public/userData.js
- Select/Deselect all users
- Selected users show up when populating user table
- Fixed logic when assigning users
- Delete assignment
- Confirm message on delete assignment and delete user
- Documentation
> Feature edit assignment fixes

- public/assignments.html
- public/createassignment.html
- public/createuser.html
- public/editAssignment.html
- public/edituser.html
- public/index.html
- public/navbar.js
- public/parameters.html
- public/rPortal.html
- public/results.html
- public/start.html
- public/userData.html
- public/userdashboard.html
Created a js file to auto generate the navbar on each page
> Feature navbar update

- public/researcher/rPortal.html
- public/researcher/rPortal.js
- public/researcher/users/createuser.html
- public/researcher/users/createuser.js
- public/researcher/users/userData.html
- public/researcher/users/userData.js
- public/spinner.css
Only added loading modals and animations to functions that accessed the cloud functions, since those were the most time consuming
> Feature loading animation

- public/navbar.js
Fixed the issue where logging in/logging out would cause the navbar links to pop in extra times
> Fixed navbar issue with popping links

- public/researcher/users/userData.js
- public/user/game/behaviours/Timer.js
Changed the way that taps are stored in the database by storing as taps as an array of csv strings. Also added cycle number to taps in database.
> Feature tapinfostorage update

- public/user/engine/base/Window.js
- public/user/game/behaviours/CircleBehaviour.js
- public/user/game/behaviours/ScoreCalculator.js
- public/user/game/behaviours/Timer.js
- public/user/graph.js
- public/user/results.html
Implemented new score algorithm
> Feature score update

- public/user/game/behaviours/CircleBehaviour.js
- public/user/game/behaviours/TapHandler.js
- public/user/graph.js
Fixed the circle indicator bug and the graph indicator not extending all the way when playing multiple cycles
> Fixed indicator bugs caused by score updates

- public/researcher/assignments/createassignment.js
- public/researcher/assignments/editAssignment.js
- public/researcher/rPortal.js
- public/researcher/users/createuser.html
- public/researcher/users/createuser.js
- public/user/edituser.html
- public/user/edituser.js
- public/user/param.js
- public/user/parameters.html
- public/user/start.html
- public/user/userdashboard.js
Added firebase listeners to prevent admins from accessing various user pages. Added null checks for input fields like the assignment name fields. Cleared user fields on success or fail of user creation
> Feature security and null checks

- public/index.html
- public/login.html
- public/researcher/assignments/assignments.html
- public/researcher/assignments/createassignment.html
- public/researcher/assignments/editAssignment.html
- public/researcher/rPortal.html
- public/researcher/users/createuser.html
- public/researcher/users/userData.html
- public/user/edituser.html
- public/user/parameters.html
- public/user/results.html
- public/user/start.html
- public/user/userdashboard.html
https://support.google.com/analytics/answer/9289234?hl=en#linkga
> Added gtag for analytics to every public html page

- public/Data.js
- public/researcher/assignments/createassignment.html
- public/researcher/assignments/createassignment.js
- public/researcher/assignments/editAssignment.html
- public/researcher/assignments/editAssignment.js
- public/user/game/behaviours/CircleBehaviour.js
- public/user/game/behaviours/TapHandler.js
- public/user/game/behaviours/Timer.js
- public/user/graph.js
- public/user/results.css
- public/user/results.html
- public/user/userdashboard.js
Implemented default assignments assigned to all users
> Feature default assignments

- public/researcher/assignments/assignments.html
- public/researcher/assignments/assignments.js
- public/researcher/assignments/editAssignment.html
- public/researcher/assignments/editAssignment.js
- public/researcher/rPortal.html
- public/researcher/rPortal.js
- public/user/userdashboard.html
- public/user/userdashboard.js
Implemented pagination on all of the tables
> Feature pagination

- public/user/game/behaviours/TextController.js
- public/user/game/behaviours/Timer.js
Moved the sound fading in when there are multiple cycles to the beginning of the sound on phase rather than the end of the sound off
> Feature soundfade update

- public/login.html
- public/researcher/assignments/editAssignment.html
- public/researcher/assignments/editAssignment.js
Fixed the select all bug where the feedback would be checked on the select all btn. Also added some UX fixes on edit assignment page & Mobile formatting stuff
> Fixed select all bug on view assignment page

- public/researcher/users/userData.html
- public/researcher/users/userData.js
Added pagination to userData (arguably the most important place)
> Implemented pagination on userData
